app = "usturz-bot"
primary_region = "fra"

[env]
  PORT = "8080"
  SERVER_MODE = "true"
  BOOKS_PATH = "/tmp/books"
  PAPER_TRADE = "true"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = true

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
